#### Notes 

    1. axis=0 denotes Y axis and axis=1 denotes X axis

    2.Be careful when copying arrays. Instead of using '=' sign, which doesn't copy something but points to the same memory location as the item to the right of '=' does, we should use copy() or deepcopy() function.

#### Import Statements 

In [1]:
import numpy as np

- Some Basic Methods

    .ndim  # Get the Dimension of an array
    .shape  # Get the Shape of an array
    .dtype  # Get the Data Type of an array
    .itemsize  # Get the memory allocation size of an item from an array (in bytes)
    .size  # Get total number of elements in an array
    .nbytes  # Get total memory allocation size of an array (in bytes)

- Creating an Array

In [2]:
a = np.array([[1, 2, 3, 3.8], [4, 5, 6, 6.7], [7, 8, 9, 9.6]])

In [3]:
b = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18]])

## Initializing Different Types of Arrays

In [4]:
# All 0s Matrix

In [5]:
np.zeros((2, 3, 2))  # takes in a tuple describing the shape of the matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
# All 1s Matrix

In [7]:
np.ones((3, 2, 3))  # takes in a tuple describing the shape of the matrix

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
# A Matrix where All the elements are same (any number)

In [9]:
print("-> A 3x3x3 Matrix of all 2s:\n")
print(np.full((3, 3, 3),
              2))  # takes in a tuple describing the shape of the matrix

print("\n->A Matrix of all 3s of the same shape as b:\n")
print(np.full_like(b, 3))  # np.full(a.shape, 3) has same effect

-> A 3x3x3 Matrix of all 2s:

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]

->A Matrix of all 3s of the same shape as b:

[[3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]]


In [10]:
# Identity Matrix of size 'n'

In [11]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


- Matrices of random numbers

In [12]:
# A Matrix of random decimal numbers between 0 and 1

In [13]:
print(np.random.rand(3, 3))

[[0.50269611 0.67079657 0.34372377]
 [0.29370556 0.59614622 0.38099417]
 [0.95967533 0.89741807 0.67851104]]


In [14]:
# A Matrix of random decimal numbers between 0 and 1 of the same shape as some predefined matrix 'a'

In [15]:
print(np.random.random_sample(b.shape))

[[0.26919591 0.75978116 0.39861991 0.66213961 0.17103676 0.19660147
  0.59136893 0.21806396 0.06841849]
 [0.63261851 0.58492853 0.13009952 0.96833613 0.36736376 0.01202519
  0.69347194 0.45846625 0.79282243]]


In [16]:
# A Matrix of random integer numbers between x and y

In [17]:
print(np.random.randint(-4, 8, size=(3, 2), dtype="int16"))  # y is exclusive

[[ 6  7]
 [ 2  0]
 [-2  3]]


In [18]:
# A random Normal Distribution 

In [54]:
np.random.randn(20)

array([-0.62542897, -0.17154826,  0.50529937, -0.26135642, -0.24274908,
       -1.45324141,  0.55458031,  0.12388091,  0.27445992, -1.52652453,
        1.65069969,  0.15433554, -0.38713994,  2.02907222, -0.04538603,
       -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655, -0.41647432])

- Numpy Random Seed

> what random.seed does is it produces an Array of Pseudo-random Numbers which is reproduceable across Notebooks if used with the same seed value.

In [20]:
np.random.seed(seed=7)
print(np.random.random((3, 4)))

[[0.07630829 0.77991879 0.43840923 0.72346518]
 [0.97798951 0.53849587 0.50112046 0.07205113]
 [0.26843898 0.4998825  0.67923    0.80373904]]


#### 3D Array Example

In [21]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(c)
# tip: to access 3d arrays work outside in

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## Accessing/Changing Specific Elements, Rows, Columns etc. (Array Slicing)

In [22]:
# Get a specific Element [r, c]

In [23]:
print(b[0, 7])
print(b[0, -2])

8
8


In [24]:
# Get a specific row

In [25]:
print(b[1, :])

[10 11 12 13 14 15 16 17 18]


In [26]:
# Get a specific column

In [27]:
print(b[:, 8])

[ 9 18]


In [28]:
# Slicing a portion out of a column or a row [start_idx:end_idx:step_size]

In [29]:
print(b[1, 8:1:-1])
print(b[0, 2:8:2])

[18 17 16 15 14 13 12]
[3 5 7]


In [30]:
# Replacing a particular element or a portion or a full row/column

In [31]:
b[0, 4] = 20
b[1, 1:4] = [22, 24, 26]
print(b)

[[ 1  2  3  4 20  6  7  8  9]
 [10 22 24 26 14 15 16 17 18]]


- Repeating an array

In [32]:
d = np.array([[1, 2, 3]])
print(d)
print(np.repeat(
    d, 3,
    axis=1))

[[1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


## (?) Exercise_01: 
    create an array that looks like this
    [[1 1 1 1 1]
     [1 0 0 0 1]
     [1 0 9 0 1]
     [1 0 0 0 1]
     [1 1 1 1 1]

In [33]:
ex_o = np.ones((5, 5))
ex_z = np.zeros((3, 3))
ex_z[1, 1] = 9
ex_o[1:-1, 1:-1] = ex_z
sol = ex_o
print(sol)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Mathematical Operations

#### Basic Arithmetic Operations

> When you perform an operation on an array, the operation gets performed on all the items. It's not same as Matrix operation instead the operation gets executed Element wise.

> Read the docs at - https://numpy.org/doc/stable/reference/routines.math.html

In [34]:
e = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
e % 2
np.cos(e)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

#### Linear Algebraic Operations

> The arrays are treated as Matrices and the operations are performed as in Matrices would.

> Read the docs at - https://numpy.org/doc/stable/reference/routines.linalg.html

In [36]:
# Multiplying two Matrices

In [37]:
mat_01 = np.ones((2, 3))
mat_02 = np.full((3, 4), 3)
mul_mat = np.matmul(mat_01, mat_02)
print(mul_mat)

[[9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [38]:
# Finding the Determinant of a Matrix

In [39]:
mat_03 = np.identity(5)
print(np.linalg.det(mat_03))

1.0


#### Statistical Operations

> Read the docs at - https://numpy.org/doc/stable/reference/routines.statistics.html

In [40]:
stats = np.array([[1, 7, 4], [8, 5, 12], [6, 13, 9], [11, 23, 1], [31, 12, 4]])
print(stats)

[[ 1  7  4]
 [ 8  5 12]
 [ 6 13  9]
 [11 23  1]
 [31 12  4]]


- Order Statistics

In [41]:
np.amax(stats, axis=1)

array([ 7, 12, 13, 23, 31])

> A percentile is a measure used in statistics indicating the value below which a given percentage
of observations in a group of observations falls. For example, the 20th percentile is the value below
which 20% of the observations may be found.

> https://www.indeed.com/career-advice/career-development/how-to-calculate-percentile

In [42]:
print(np.percentile(stats, 50, axis=0))

[ 8. 12.  4.]


> quantiles are cut points dividing the range of a probability distribution into continuous intervals
with equal probabilities

In [43]:
print(np.quantile(stats, 0.5, axis=1))

[ 4.  8.  9. 11. 12.]


- Averages and variances

In [44]:
print(np.mean(stats, axis=0))
print(np.average(stats, axis=1))

[11.4 12.   6. ]
[ 4.          8.33333333  9.33333333 11.66666667 15.66666667]


In [45]:
print(np.median(stats))

8.0


## Reorganizing Arrays

#### Reshaping Arrays

> For any arrays that has a shape of - before: (shape of axb) and after: (shape of cxd) ; reshaping works as long as ab = cd.

In [46]:
before = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
after = before.reshape((5, 2))
print(after)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


- Transpose of an Array

In [47]:
print(after.T)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


#### Stacking Arrays

- Vertical Stacking

In [48]:
# for this to work all the vectors to be stacked must have the same number of columns
v1 = np.array([[1, 2, 3], [4, 5, 6]])
v2 = np.array([7, 8, 9])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Horizontal Stacking

In [49]:
# for this to work all the vectors to be stacked must have the same number of rows
h1 = np.array([[1, 2, 3], [4, 5, 6]])
h2 = np.array([[7, 8, 9, 13], [10, 11, 12, 14]])
np.hstack((h1, h2))

array([[ 1,  2,  3,  7,  8,  9, 13],
       [ 4,  5,  6, 10, 11, 12, 14]])

------------------

### Load Data from a file

In [50]:
filedata = np.genfromtxt("NumpySampleData.txt", dtype="int32", delimiter=",")
print(filedata)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


---------------

## Advanced Indexing

- From an existing Array, Grab and Create an Array of values that fulfills some sort of condition(s)

In [51]:
new_arr = filedata[(filedata / 2) >= 7]
print(new_arr)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [52]:
# This works because you can actually index with a list in numpy
f = new_arr[[1, 3, 8]]
print(f)

[15 17 22]


## (?) Exercise_02:
    get [2, 8, 14, 20] from the given array - 
    
    g = 
    [[1,2,3,4,5], 
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]]

In [53]:
g = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20]])
sol_2 = g[[0, 1, 2, 3], [1, 2, 3, 4]]
print(sol_2)
w_sol = g[0:4, 1:5]
print(w_sol)

[ 2  8 14 20]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
